# Generated by Django 4.1 on 2022-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('IM', 'Image'), ('DB', 'Database'), ('VD', 'Video')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('RS', 'ReadSheet'), ('MS', 'MasterSheet'), ('IS', 'InterpretationSheet'), ('WS', 'WriteSheet'), ('AS', 'AAOutput')], max_length=2)),
            ],
        ),
    ]
