# Generated by Django 4.1 on 2022-10-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='test_sheets')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
