# Generated by Django 4.1 on 2022-08-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_admin', '0003_database_excel_images_bot_interpretationsheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database_excel',
            name='file',
            field=models.FileField(upload_to='attachments/database'),
        ),
        migrations.AlterField(
            model_name='images_bot',
            name='file',
            field=models.FileField(upload_to='attachments/images'),
        ),
        migrations.AlterField(
            model_name='interpretationsheet',
            name='file',
            field=models.FileField(upload_to='Interpretation_sheets'),
        ),
        migrations.AlterField(
            model_name='readsheet',
            name='file',
            field=models.FileField(upload_to='read_sheets'),
        ),
    ]
